### ISSUE TITLE
Bug rendering Old Hangul with tone marks vertically

### ISSUE THREAD

**Issue by mujjingun** [harfbuzz/harfbuzz#293]
Run command:
`type input.txt | hb-view.exe C:\WINDOWS\Fonts\NANUMBARUNGOTHIC-YETHANGUL.TTF --output-format=png --output-file=image.png --direction=ttb`

input.txt(This is the first line of the [Hunminjeongeum Eonhae](https://en.wikipedia.org/wiki/Hunminjeongeum)):
`나랏〮말〯ᄊᆞ미〮`

image.png(output):
![image](https://cloud.githubusercontent.com/assets/6328181/16865385/3ee16706-4a9f-11e6-97a9-b2e73e5d7ad8.png)

The width of the image is too small, also the tone marks should be put on the left side of each character.

Expected output(made using Photoshop):
![correct](https://cloud.githubusercontent.com/assets/6328181/16865535/729b614a-4aa0-11e6-9642-5f12a1534e45.png)

The tone marks combined with the syllables should make one block to be written vertically.

I'm using [NanumBarunGothic YetHangul](https://github.com/ujuc/nanum-font/blob/master/ttf/NanumBarunGothic-YetHangul.ttf) for the font.

**Comment by KrasnayaPloshchad** [comment]
What would be happened if you are using [Source Han Sans K](https://github.com/adobe-fonts/source-han-sans)?

**Comment by mujjingun** [comment]
Using Source Han Sans K,

    type input.txt | hb-view.exe C:\WINDOWS\Fonts\SOURCEHANSANSK-MEDIUM.OTF --output-format=png --output-file=image.png --direction=ttb

result:
![image](https://cloud.githubusercontent.com/assets/6328181/16899364/90037b08-4c3c-11e6-89cc-84b871ee0376.png)

The problem of tone marks appearing above each character is fixed, but the image is still too small in width. I manually increased image size by setting --margin=200, and it revealed another problem:

![image](https://cloud.githubusercontent.com/assets/6328181/16899371/b2d5a854-4c3c-11e6-9515-87ce0ee4bbbe.png)

The tone marks are too high up. It should align at the vertical center of each glyph, just like how it renders in left-to-right:
![image](https://cloud.githubusercontent.com/assets/6328181/16899376/de2ce0a8-4c3c-11e6-9960-a9a8ee39aef8.png)

**Comment by KrasnayaPloshchad** [comment]
CC @kenlunde

**Comment by kenlunde** [comment]
The use of U+302E and U+302F in vertical writing was thoroughly explored about two years ago, and Version 1.001 issued a fix that was working at the time. My guess is that something not related to the font broke this.

**Comment by KrasnayaPloshchad** [comment]
It seems to me that this issue is caused by HB itself, and both NanumBarunGothic YetHangul and Source Han Sans are suitable for test.

**Comment by KrasnayaPloshchad** [comment]
cc @khaledhosny

**Comment by KrasnayaPloshchad** [comment]
This problem is also appearing to me when I decreased image size by setting `--margin=150`.

![image](https://cloud.githubusercontent.com/assets/10364351/17084009/baec3dac-51e4-11e6-8e24-ab032f6cd9b9.png)

**Comment by KrasnayaPloshchad** [comment]
CC @jfkthame

**Comment by KrasnayaPloshchad** [comment]
I have just tested with Firefox, they works very well.
![1](https://cloud.githubusercontent.com/assets/10364351/19847045/e09f7cde-9f7e-11e6-88e9-27db38534103.PNG)
![2](https://cloud.githubusercontent.com/assets/10364351/19847056/ed15c54a-9f7e-11e6-9b5b-4611a10acfa2.PNG)
So how does Firefox get the solution?

**Comment by behdad** [comment]
I fixed the margin issue in master.  Can someone check?  Is there anything else to be done here?

**Comment by KrasnayaPloshchad** [comment]
I have tested with current version of hb-view, but the problem still appearing. When I test it with LibreOfficeDev 5.3 (which use new layout engine based on HarfBuzz), tone marks works proper when I display with Source Han Sans, but to my surprise, ᄊ + ᆞ works only with Korean.
![default](https://cloud.githubusercontent.com/assets/10364351/19916110/13131094-a0f2-11e6-9c37-67b3ecf0a632.PNG)

**Comment by kenlunde** [comment]
The 'ljmo', 'vjmo', and 'tjmo' GSUB features in Noto Sans CJK / Source Han Sans, which affect ᄊ + ᆞ, are associated with the 'hang' script and the 'dflt' and 'KOR' languages.

**Comment by KrasnayaPloshchad** [comment]
OK, it seems to me that there is a bug affect hb-view.

**Comment by behdad** [comment]
@kenlunde @jungshik do you know what needs to be done here?

**Comment by kenlunde** [comment]
@behdad: I am not sure. I would think that the first order of business would be to retest using the latest builds of the affected environments, to confirm whether this issue persists.

**Comment by KrasnayaPloshchad** [comment]
This bug still appearing when I test with hb-view v1.5.1 and Source Han Serif v1.001, both horizontal and vertical text layout have been affected.
![1](https://i.imgur.com/ZdqwQcx.png)
![2](https://i.imgur.com/VJBvDgW.png)

**Comment by KrasnayaPloshchad** [comment]
LibreOfficeDev 6.0.0.0.alpha0+ release (libo-master64~2017-09-13_22.53.00_LibreOfficeDev_6.0.0.0.alpha0_Win_x64) performanced the same.
![1](https://i.imgur.com/nmsPqfl.png)

**Comment by KrasnayaPloshchad** [comment]
After I update hb-view to 2.1.1, the problem is still there.
![hunmin-jeongeum-2](https://user-images.githubusercontent.com/10364351/48298878-b404d400-e4bc-11e8-9a0a-ebd41323c156.png)

**Comment by mujjingun** [comment]
Still no fix?

**Comment by mujjingun** [comment]
Bug persists in latest commit 302bde0b.
<img src="https://user-images.githubusercontent.com/6328181/129184252-c2f007e1-8234-47db-a634-71d78e164794.png" width="100" />

**Comment by mujjingun** [comment]
I have found the culprit: [This bug](https://gitlab.freedesktop.org/freetype/freetype/-/issues/1102) from FreeType.

**Comment by behdad** [comment]
> I have found the culprit: [This bug](https://gitlab.freedesktop.org/freetype/freetype/-/issues/1102) from FreeType.

Gah. Thanks.
